version: '3.9'
networks:
  app_network:
services:
  db:
    container_name: postgres_db
    build: ./db_data
    ports:
      - "5432:5432"
    networks:
      - app_network

  flask_app:
    container_name: flask_app
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - app_network
